### ISSUE TITLE
Arglist question with .

### ISSUE THREAD

**Issue by cyansprite** [justinmk/vim-dirvish#91] opened 2017-09-07 21:49 UTC
If I use . on the same file, it adds it over and over,
is there a vim strategy to have the same file in the arglist?
If not filtering my be a nice option for .

**Comment by justinmk** [comment] 2017-09-07 22:00
Can't reproduce. Need precise steps.

**Comment by cyansprite** [comment] 2017-09-07 22:52
I haven't touched settings first time using it.

i did
´´´bash
cd ~/.config/nvim
vim plug.vim
´´´

then in vim
´´´vim
:Dirvish
´´´
(cursor to plug.vim by using j)
j
....... (. to add to arg list)

now args are filled with plug.vim

**Comment by justinmk** [comment] 2017-10-07 16:49
Yeah, this happens on linux too. The args list refuses to store a full path, so dirvish's attempts to de-duplicate fail.

**Comment by justinmk** [comment] 2017-10-07 23:30
@cyansprite should be fixed, thanks for the report.

**Closed** 2017-10-07 23:30 UTC
