### ISSUE TITLE
Relax file-existence check (WAS: MRU feature)

### ISSUE THREAD

**Issue by Asheq** [justinmk/vim-dirvish#129] opened 2018-08-16 01:32 UTC
It would be amazing to get a listing of the most-recently used (MRU) files shown in order of recency in a Dirvish buffer. 

Using Dirvish is so fast and fluid and I want to be able to use it for more types of file listings. I am enticed by the idea of quickly opening an MRU Dirvish buffer and only having to tap `j` a couple times to have my cursor over a recently-used filename.

Just wanted to throw this idea out in case you liked it and it is easy to implement, or if you have any wisdom to share on how I might implement it myself. Thanks!

**Comment by justinmk** [comment] 2018-08-16 09:25
Dirvish [was designed](https://github.com/justinmk/vim-dirvish#concepts) to be flexible enough (or dumb enough) to support any case where you have a list of paths. So `:set filetype=dirvish` enables Dirvish features on any buffer.

It's up to you to get the paths into the buffer. Example for `:ls`: https://twitter.com/airblade/status/1027117422451609605

    :new
    :0put=execute('ls')
    :%s/\v.{-}"(.*)".*/\=fnamemodify(submatch(1),':p')/
    :set ft=dirvish

In your case you want to massage `:oldfiles` instead of `:ls`. Here's a starting point for that:

    :new
    :0put=execute('oldfiles')
    :keeppatterns %s/\v.{-} (.*)/\=fnamemodify(submatch(1),':p')/
    :set ft=dirvish

The `fnamemodify(submatch(1),':p')` is important because Dirvish works best with absolute paths. 

# Enhancement

I notice that Dirvish complains about non-existent paths, e.g. fugitive URIs:

    dirvish: invalid (or access denied): fugitive:///home/foo/neovim/.git//ae24c9b27016a841121b1a01664b748b0a5cbeb7/src/nvim/mark.c

I guess this case could be improved by trying to open the buffer and let Vim decide what to do with it.

**Comment by Asheq** [comment] 2018-08-16 23:08
Oh awesome, that's fairly simple!

BTW, it seems that `:oldfiles` isn't updated until vim is closed. There are other plugins that keep a list of MRU files while vim is actually running (by updating the list when BufWinEnter,WinEnter autocmds are triggered). I think I can leverage the functions from those plugins and use the pattern above to get what I want!

**Comment by justinmk** [comment] 2019-03-27 15:44
Addressed by 3dc59a7c0741b76bf1f8c81ef560035389f9b4d5 #127

**Closed by justinmk** 2019-03-27 15:44 UTC
Labels: enhancement, question
