### ISSUE TITLE
Alternate buffer when opening darvish as first buffer.

### ISSUE THREAD

**Issue by vheon** [justinmk/vim-dirvish#8] opened 2015-03-12 12:27 UTC
I don't know if this is the expected behaviour but if I do:

* `vim .`, the darvish buffer opens
* press `Enter` on a file, the file is open.
* press `<C-6>` I get back to the darvish buffer

I was expecting nothing to change.

**Comment by justinmk** [comment] 2015-03-12 13:35
if you have any other buffer open it will prefer that instead. Given that, this is a pretty minor edge case.

**Comment by vheon** [comment] 2015-03-12 14:40
On a side question: to benefit the goodies of this plugin is required to use `:Dirvish` or I can use the regular `:e` command?

**Comment by justinmk** [comment] 2015-03-12 15:09
`:e` should work fine. Only problem with `:e <dir>` I have noticed is the "Illegal file name" message, which is just a cosmetic annoyance.

A benefit of `:Dirvish` is that if the path is a filename (including `%` and `#`), it will open the parent directory. If you want "vim-vinegar" functionality, just map this:

     nnoremap - :Dirvish %<cr>

**Comment by vheon** [comment] 2015-03-12 19:29
I was asking because for me `:e` do not work:

* I enter vim and open a file
* `:e .` and the dirvish open
* press `Enter` on another file to open it
* `<C-6>` it brings me back to the dirvish buffer. 

If instead of `:e .` I use `:Dirvish .` everything works fine.

**Comment by justinmk** [comment] 2015-03-12 20:43
Even on latest (after 0dda6c1d6bd6bb540b42135d90e8e904fead758c)? I can't reproduce (vim 7.4.430, or neovim).

[I'm actually shocked that it *does* work, however, because we depend on BufEnter event, during which I would have assumed `@#` was already clobbered.]

**Comment by vheon** [comment] 2015-03-12 21:03
I just updated to the latest, and ether with vim 7.4.481 or neovim everything works with `:Dirvish` but not with `:e`

**Comment by justinmk** [comment] 2015-03-12 21:16
Oh, I misread your steps in https://github.com/justinmk/vim-dirvish/issues/8#issuecomment-78583240 ,  they are essentially the same steps as your first post in this issue. And just to be clear, the only problem is that you want it to report "no alternate buffer" or something like that? 

Here is what is happening: the Dirvish buffer is unloaded, but still present in the `:ls!` buffer list. Vim has marked it as the alternate buffer because Dirvish couldn't find *any other buffer* to substitute as the alternate buffer. This will *only* happen in the very specific case where you have a single buffer open. To avoid it, the plugin would need to do some logic to temporarily trick Vim into marking an empty buffer as the alternate, then `:bwipe` it. Doesn't seem worth it.

**Comment by vheon** [comment] 2015-03-12 22:10
So for the case where I start with vim with a directory like `vim .` I have to live with this and is not that bad. The problem that I am have now is that in every case I open a directory with `:e` instead that `:Dirvish` the dirvish buffer is always set as the alternative buffer. So even If I have opened multiple buffer, as soon as I open a directory with `:e directory` the dirvish buffer is what I get with `<C-6>`, and I wanted to know if that was the intended behaviour and I'm supposed to use `:Darvish directory` instead. Sorry If I didn't explain myself well.

**Comment by justinmk** [comment] 2015-03-12 22:21
Oh, that's definitely a problem. 

> dirvish buffer is always set as the alternative buffer

Before you `:e <dir>`, what is the value of `bufnr('#')`?

**Comment by justinmk** [comment] 2015-03-12 22:27
Nevermind, I can reproduce it.

**Comment by justinmk** [comment] 2015-03-12 23:20
Should be fixed now, thanks for helping narrow it down.

**Closed** 2015-03-12 23:20 UTC
