### ISSUE TITLE
Opened file doesn't detect the filetype

### ISSUE THREAD

**Issue by LemonBoy** [justinmk/vim-dirvish#13] opened 2015-10-03 11:16 UTC
I'm using the latest version, when I browse a folder and then open a file (from dirvish itself or via ctrlp) the filetype detection doesn't kick in.
It didn't happen with `ae206266555ff3e81db9f45fa54dbcb3a1a07a49` nor it happens with netrw.

**Comment by justinmk** [comment] 2015-10-03 15:07
Whoops! Got a little exuberant there. Fixed now.

**Comment by LemonBoy** [comment] 2015-10-05 15:27
Hmm, I have just updated dirvish and it seems to still suffer from this.

**Comment by justinmk** [comment] 2015-10-05 16:06
@LemonBoy There's an edge case where it still happens if dirvish is the first thing you open, or it's the only thing open, something like that. Will fix later today.

**Comment by justinmk** [comment] 2015-10-08 19:06
@LemonBoy Fixed

**Comment by tummychow** [comment] 2015-12-27 01:43
I'm in neovim 0.1.1 with dirvish `4826eb4284b3b2390d9761e0ccc48a00e4b71be9`, and I'm also getting this issue.

If I go all the way back to LemonBoy's recommended commit `ae206266555ff3e81db9f45fa54dbcb3a1a07a49`, the issue disappears. However, the commit `008c1133ca250c22201c971915b5c19034e231c5` still has this problem.

**Comment by justinmk** [comment] 2015-12-27 02:19
@tummychow I reproduced the issue, but can you confirm these details:

- issue only occurs for _first_ file opened (via `i` or `<enter>`)
    - if I browse again and select a different file, that file is syntax-highlighted
- issue does _not_ occur if I open a file in a new window (via `a` or `o`)

I used the following to repro:

    vim -u NONE -N  -c ':set runtimepath+=~/.vim/bundle/vim-dirvish/' -c ':runtime plugin/dirvish.vim' -c 'filetype plugin indent on' -c 'syntax on'

**Comment by tummychow** [comment] 2015-12-27 02:26
Thanks for the very quick response!

On your first question: not sure if I'm reproing the way you are, but here's what I've got:

- I open a file in the dirvish window: filetype not detected. Then I `:Dirvish %` in that window, and open in that window: filetype also not detected.
- if I open a file in a new window: filetype detected. Then, going back to the dirvish window, I open another file in the dirvish window: this filetype is also detected.

Was that what you were asking? Sorry if I misunderstood.

As for your second question - yup, opening from dirvish into another window has no filetype issues.

**Comment by justinmk** [comment] 2015-12-27 03:31
> Then I :Dirvish % in that window, and open in that window again: filetype also not detected.

Opened the same file again, or a different file?

**Comment by tummychow** [comment] 2015-12-27 03:33
Ah good question - same file. If I open a different file in that situation, its filetype gets detected.

**Comment by justinmk** [comment] 2016-01-06 08:08
@tummychow This is apparently a very subtle Vim bug related to the `hidden` option.

Do you not `set hidden` ? (What's the value of `:set hidden?`)

**Comment by tummychow** [comment] 2016-01-06 14:32
You're right, I didn't have `hidden` on. With `hidden` set, the bug goes away.

I tried pulling master with your commit above and `hidden` off. The behavior changed, but there still seems to be a bug. Now I can do this:

- open a file in the dirvish window; its filetype is detected
- `:Dirvish %` in that window
- open the same file in that dirvish window, now its filetype is not detected

Judging by your commit message, it sounds like you were expecting this, just wanted to let you know it was there. Personally I'm okay with setting `hidden` as a workaround for this, but if you want to keep investigating I'd be glad to help with that as well.

**Comment by justinmk** [comment] 2016-01-06 15:14
@tummychow Thanks for follow-up. I do plan to fix the remaining issue, just need to think about the right way to do it.

**Closed** 2016-02-04 08:20 UTC

**Comment by justinmk** [comment] 2016-02-04 08:46
@tummychow Should be fixed for `nohidden` now.

**Comment by tummychow** [comment] 2016-02-04 09:07
:+1: works like a charm, thanks!
